"""Create tables

Revision ID: f9c3abad84f7
Revises: 
Create Date: 2019-12-17 23:57:24.300449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c3abad84f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('accountID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('displayName', sa.String(length=30), nullable=True),
    sa.Column('profileInfo', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('accountID'),
    sa.UniqueConstraint('avatar')
    )
    op.create_index(op.f('ix_account_displayName'), 'account', ['displayName'], unique=False)
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('category',
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('categoryID')
    )
    op.create_index(op.f('ix_category_categoryName'), 'category', ['categoryName'], unique=True)
    op.create_table('friend',
    sa.Column('friendID', sa.Integer(), nullable=False),
    sa.Column('accountID', sa.Integer(), nullable=True),
    sa.Column('friendAccountID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountID'], ['account.accountID'], ),
    sa.PrimaryKeyConstraint('friendID')
    )
    op.create_table('post',
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('accountID', sa.Integer(), nullable=True),
    sa.Column('categoryID', sa.Integer(), nullable=True),
    sa.Column('postContent', sa.String(length=150), nullable=True),
    sa.Column('postImage', sa.String(length=100), nullable=True),
    sa.Column('postLikeNumber', sa.Integer(), nullable=True),
    sa.Column('postLikeAccount', sa.Integer(), nullable=True),
    sa.Column('postCheck', sa.Boolean(), nullable=True),
    sa.Column('postLocation', sa.String(length=30), nullable=True),
    sa.Column('postTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accountID'], ['account.accountID'], ),
    sa.ForeignKeyConstraint(['categoryID'], ['category.categoryID'], ),
    sa.PrimaryKeyConstraint('postID')
    )
    op.create_table('comment',
    sa.Column('commentID', sa.Integer(), nullable=False),
    sa.Column('postID', sa.Integer(), nullable=True),
    sa.Column('accountID', sa.Integer(), nullable=True),
    sa.Column('commentContent', sa.String(length=100), nullable=True),
    sa.Column('commentImage', sa.String(length=100), nullable=True),
    sa.Column('commentTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accountID'], ['account.accountID'], ),
    sa.ForeignKeyConstraint(['postID'], ['post.postID'], ),
    sa.PrimaryKeyConstraint('commentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('friend')
    op.drop_index(op.f('ix_category_categoryName'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_index(op.f('ix_account_displayName'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
